### ISSUE TITLE
Installation: downloading Kalabox?

### ISSUE THREAD

**Issue by kopeboy** [kalamuna/kalastack#105]
If I understand correctly Kalabox is a GUI "add-on" to Kalastack. Following the installation process in the kalastack/readme.md will download "kalabox", which is never mentioned in the readme.

(I had problems with my one of my Pantheon sites, which couldn't work on local, so I wanted to uninstall everything and restart, included Vagrant & Vitrualbox)

**Comment by pirog** [comment]
Kalabox uses kalastack but it isn't an "add-on" to kalastack in the sense that you can download and install kalastack and then do something else to get kalabox.

If you want Kalabox i would just download the dmg from https://github.com/kalamuna/kalaboxv1/releases

**Comment by kopeboy** [comment]
Ok thanks. I didn't want kalabox. It was just misleading naming: I was installing "kalastack 3" and then at http://start.kala I see "kalabox 2"
