### ISSUE TITLE
provide some default shell environment configuration files

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalastack#13]
git config colors? basic bash aliases?

**Comment by pirog** [comment]
@andrewmallis post your shiz up here for me to use

**Comment by andrewmallis** [comment]
if the user SSH'es into the server and run git there, we should have a `.gitignore` in the vagrant home directory:

```
*DS_Store*
.settings
.buildpath
.project
.vagrant
```

**Comment by andrewmallis** [comment]
we should also copy the .git-completion.bash file that ships with git, though this should be part of puppet for git.

`sudo apt-get install git-core bash-completion` is recommended here: https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion

I've typically just copied the file to my ~/ but a smarter solution pointing to source would be better.

**Comment by pirog** [comment]
im going to use https://github.com/whastings as a basis for some of this

**Comment by andrewmallis** [comment]
if [ -f ~/.git-completion.bash ]; then
. ~/.git-completion.bash
fi

once the compeltion is in there…

**Comment by pirog** [comment]
mallis money ftw
