### ISSUE TITLE
investigate sql-sync-pipe to speed up DB sync

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalastack#14]
Interesting approach to Db sync from pantheon that pipes the output into gzip for faster transfer:

https://github.com/markcarver/sql-sync-pipe

also 

some overlap with [pandarus](http://drupal.org/project/Pandarus) but seems better.

**Comment by andrewmallis** [comment]
[This pantheon helpdesk issue](http://help.getpantheon.com/pantheon/topics/drush_sql_sync_does_not_work#reply_12223281) points to sql-sync being supported now with updated alias files.

We can install the drush extension in the stack once we upload drush with something like:

```
drush dl drush_sql_sync_pipe --destination=$HOME/.drush
```

**Comment by andrewmallis** [comment]
from the project page: https://drupal.org/project/drush_sql_sync_pipe

> If you have [Pipe Viewer](http://www.ivarch.com/programs/pv.shtml) installed, you can pass the --progress option to show syncing progress between the source and destination.

**Comment by pirog** [comment]
this will be in beta1... we will need to test it ... not sure it is that much faster yet
