### ISSUE TITLE
Leverage community modules

### ISSUE THREAD

**Issue by patcon** [kalamuna/kalastack#2]
Here are some reliable community modules that we might be able to pull in via librarian-puppet support:
- https://github.com/puppetlabs/puppetlabs-motd
- https://github.com/puppetlabs/puppetlabs-git
- https://github.com/puppetlabs/puppetlabs-apt
- https://github.com/puppetlabs/puppetlabs-nginx
- https://github.com/puppetlabs/puppetlabs-mysql
- https://github.com/puppetlabs/puppetlabs-puppet (?)

**Comment by patcon** [comment]
https://github.com/saz/puppet-php
https://github.com/example42/puppet-mysql

Can steal approaches from this:
https://github.com/dirkaholic/vagrant-php-dev-box/tree/master/puppet/modules

**Comment by patcon** [comment]
https://github.com/treehouseagency/puppet-pear
https://github.com/BenoitCattie/puppet-nginx

https://github.com/example42/puppet-solr/
https://github.com/KrisBuytaert/puppet-solr

**Comment by pirog** [comment]
yes. we want a 3.x branch of kalastack to built on community sources modules!

**Comment by pirog** [comment]
3.x branch of kalastack is now 1.x branch of https://github.com/proviso/proviso
