### ISSUE TITLE
Use vagrant-puppetconf rather than in the script provisioner

### ISSUE THREAD

**Issue by patcon** [kalamuna/kalastack#22]
Would this work for y'all?
https://github.com/gposton/vagrant-puppetconf

I'd be happy to put some time into updating the plugin to v2 if you're down with it. I think it would make the setup happening in the vagrantfile much more clear :)

**Comment by pirog** [comment]
added some ruby magix to the vagrant file and was able to remove the need for that jank ass shell provisioner and by extension i dont think we need this plugin either anymore. holla!
