### ISSUE TITLE
set some sane defaults for user config without borking the box and providing a config pathway that doesnt wipe out the users customizations

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalastack#31]
we have already pulled in some useful config from https://github.com/whastings/dot-files but we need to get the aliases and exports files to work. 

this stuff should go into the user class.

**Comment by pirog** [comment]
@andrewmallis if you and will could figure out the best way to handle settings some good config but also not wiping out changes on subsequent provisions that would be swell

**Comment by whastings** [comment]
So far, I'm thinking the following customizations would be helpful out of the box:
- .git-completion.bash (which we have already)
- .git-config (We can use this to set nice colors in git output. We have this already, but we've put it in the home folder. We're thinking it would be good to move this to the system-level gitconfig so the user can override things in her ~/.gitconfig if desired
- Prompt string: Give a nice looking, concise prompt that's color differently than default terminal output
- .gitignore (To ignore common IDE/editor generated files. We pretty much have this already at ~/.gitignore, but can add to it).
- colors (Export some color variables that we can use to style things like the prompt).

We also need to figure out how to source our shell customization. Right now, we're overwriting Ubuntu's default .bashrc. We should change this to either append our customizations to the end of the default, or else use a different file like .bash_profile or .profile. I need to figure out how/when Ubuntu sources these other files though.

**Comment by pirog** [comment]
@whastings @andrewmallis hey guys, im fine with you guys directly committing whatever you come up with. At the same time if it makes you feel more comfortable having me look at it first you can alternatively submit a pull request.

**Comment by whastings** [comment]
FYI, if we create a .bash_profile, .bashrc won't get sourced.

**Comment by whastings** [comment]
Also, we may want to put important Bash commands, like setting the KALABOX environment variable, in a safer place than .bashrc.

**Comment by pirog** [comment]
followed some better procedures here to move global config out of user config and to append to files missing needed conf vs overwriting them. 

you might want to destroy and rebuild.

**Comment by pirog** [comment]
this will be in beta6
