### ISSUE TITLE
verify solr works

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalastack#33]

**Comment by andrewmallis** [comment]
1. pantheon_api, pantheon_apachesolr were not disabled automagically; not sure if they're supposed to be via the new sql-sync flags.
2. i was able to re-index and successfully get results out of the Occupy Directory project.

**Comment by pirog** [comment]
1. should only try to disable pantheon_apachesolr i think its fine for the api to stay on. ill give this a test a little later. 
2. this is good but i think its only because the directory is using the old patched rc4 search_api and we are shipping with those schemas in the stack. we should try this on a different site because i suspect it will not work. we need to get up to speed with the new search api and apchesolr mods/schemas.

**Comment by pirog** [comment]
solr works but you still need to copy schema/solrconfig/etc to the solr conf directory to get it to work... might want a better option similar to pantheons "post schema"

**Comment by pirog** [comment]
we are going to put the solr schema posting mechanism into the kalabox config. probably easier for the user and less intrusive then requiring a custom drupal module. 

that said i am going to provide another "env variable" that when set will install solr. this way we can have a spin up button on the box.

**Comment by pirog** [comment]
to install solr via the stack as an add on you now set the environmental variable on the command line

$ export KALABOX_SOLR=TRUE
$ vagrant up
