### ISSUE TITLE
php.kala and grind.kala don't function on OS 10.7

### ISSUE THREAD

**Issue by reynoldsalec** [kalamuna/kalastack#34]
php.kala, grind.kala, and php.kala, despite being correctly inserted into /etc/hosts on the host machine, aren't functional. However, if you attempt visiting solr.kala, you are taken to php.kala.

start.kala functions as expected.

**Comment by reynoldsalec** [comment]
I think this was user error, not 10.7, on my machine. I had Kalabox stuff from the old Kalabox installer AND entries from the original Kalabox in my hosts file. After removing those everything is cool. If @pirog had issues on another computer we might want to make sure funk wasn't going on in that hosts file. Closing unless that turns out to be the case.

**Comment by pirog** [comment]
@reynoldsalec as soon as we get a power supply for the old laptop lets def check to see if the same thing was happening on that machine.
