### ISSUE TITLE
Provide a Drupal site out of the box (no pun intended)

### ISSUE THREAD

**Issue by whastings** [kalamuna/kalastack#36]
@pirog Is it still planned to have one Drupal site running on the just-installed box? Maybe at start.kala?

**Comment by pirog** [comment]
yeah definitely. might want to do something besides start.kala... mysite.kala or something lame like that.

in terms of implementation maybe it would make most sense to leverage drush for this vs shipping with it already installed? not sure.

**Comment by whastings** [comment]
I like the idea of using Drush to build it. Perhaps the best approach would be to work on the custom Drush command for spinning up a local site (i.e. like drush build does for Pantheon, but without the need for a Pantheon site to start from). Then we could have Puppet run this command to create an initial Drupal site for the user.

**Comment by reynoldsalec** [comment]
Should be able to do this with drush dl drupal and drush si (site-install), more or less. Might merit a separate drush script if there are any additional things we need to do.

**Comment by whastings** [comment]
Sounds good. Could we write a command that uses these two commands, as well as sets up a Nginx vhost and database?

**Comment by pirog** [comment]
yup, exactly what i was thinking. should already be a vhost/db command we can leverage. will probably have to use the settings rebuilder as well.

**Comment by pirog** [comment]
an updated drush build command that lets you spin up new distros will be in the beta6 release
