### ISSUE TITLE
figure out host updater funk

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalastack#38]

**Comment by whastings** [comment]
Turned out this was just an issue with the plugin and Vagrant 1.1.2. Upgrading to 1.2.2 fixed it, so I've updated the README to reflect 1.2.2 as the required Vagrant version.

**Comment by andrewmallis** [comment]
@whastings with the smackdown!

**Comment by whastings** [comment]
Lol, thanks but it was @pirog that thought to try upgrading Vagrant.
