### ISSUE TITLE
Use `localhost` as mysql server rather than `kala`

### ISSUE THREAD

**Issue by patcon** [kalamuna/kalastack#4]
The kala drush commands and some of the modules expect to community with mysql at the server `kala`. Can this just be `localhost` for now? For whatever, it seems that accessing mysql through `kala` rather than localhost (after simplifying the `hosts` file), doesn't work smoothly. I'm sure we can figure it out later (if using vagrant ends up making sense), but it would help for now.

Any particular reason it must be `kala`, or was it just a preference for organizing things?
https://github.com/kalamuna/kalabox/blob/1.x/modules/drush/files/kala.drush.inc#L293

**Comment by kellybell** [comment]
I agree, would prefer `localhost`.

**Comment by pirog** [comment]
i think this has changed when we moved to vagrant
