### ISSUE TITLE
location of drush alias file reported on guest system could be disambiguated

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastack#43]
Drush alias file location reported on guest system reports:

```
$ drush st

PHP configuration    :  /etc/php5/cli/php.ini
Drush version        :  5.9
Drush configuration  :  /etc/drush/drushrc.php
Drush alias files    :  /var/www/.drush/aliases.drushrc.php
```

Since /var/www/ maps to ~/kalabox/www/
The user might expect their host system at ~/kalabox/www/.drush to contain aliases.drushrc.php

**Comment by andrewmallis** [comment]
Instead of

```
  config.vm.synced_folder "~/kalabox/drush", "/var/www/.drush", :create => true, :nfs => true
```

let's use

```
  config.vm.synced_folder "~/kalabox/drush", "/home/vagrant/.drush", :create => true, :nfs => true
```

**Comment by andrewmallis** [comment]
commit 19d12cd483dc0e67c1958fba18bfa0c2c9190a23 implements this change.

**Comment by pirog** [comment]
please revert this change and submit a pull request. we need to discuss this change more before we commit it.

**Comment by andrewmallis** [comment]
reverted as this exposes cache folder to user and that's no good.

**Comment by pirog** [comment]
going to move this to /etc/drush... as @andrewmallis points out it is awkward in the /var/www/.drush. 

will be in beta6
