### ISSUE TITLE
set vm memory to some percentage of available host memory and use that to allocate guest resources

### ISSUE THREAD

**Issue by pirog** [kalamuna/kalastack#44]

**Comment by whastings** [comment]
@pirog For the meantime, I listed the 2GB RAM default under Quickstart in the README and created a wiki page with instructions on lowering the amount of RAM in the Vagrantfile. We should be able to remove these once this issue is complete.

**Comment by pirog** [comment]
@whastings agreed. looked around in the ruby docs for a way to check "available memory"... couple possible pathways there. any thoughts on how to do this?

**Comment by whastings** [comment]
I did some searching and found a couple contributed Ruby libraries that do it, but neither of them come with Vagrant. It looks like we can determine it through the command line via this command:

```
system_profiler SPHardwareDataType
```

On my computer, one of the lines it yielded was: `Memory: 8 GB`

**Comment by pirog** [comment]
awesome. i saw that as well. gotta figure out how to integrate it.

what do you think is a reasonable % of memory to allocate to the VM?

On Wed, Jul 24, 2013 at 12:52 PM, Will Hastings notifications@github.comwrote:

> I did some searching and found a couple contributed Ruby libraries that do
> it, but neither of them come with Vagrant. It looks like we can determine
> it through the command line via this command:
> 
> system_profiler SPHardwareDataType
> 
> On my computer, one of the lines it yielded was: Memory: 8 GB
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kalamuna/kalastack/issues/44#issuecomment-21498945
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by whastings** [comment]
I think it should be easy to run the command from Ruby in the Vagrantfile, then parse the output with a simple regex.

For memory percentage, I'm thinking something like:
- 25% of host memory in general.
- Maybe a 1GB memory minimum? What we should probably do is look at the max memory we're allocating to nginx, MySQL, and PHP, add it to Ubuntu's base memory requirements, and use that to determine and accurate memory minimum.

**Comment by pirog** [comment]
set on the vagrantfile side... need to allocate in puppet based on that number still

**Comment by pirog** [comment]
this should allocate some basic stuff php, apc, mysql based on the users total mem
