### ISSUE TITLE
Mac OS firewall interferes with box when enabled

### ISSUE THREAD

**Issue by whastings** [kalamuna/kalastack#45]
I've identified two problems that occur when the Mac firewall is enabled:
1. When the firewall is on and "Block all incoming connections" is checked under "Firewall Options", NFS mounting fails
2. When the firewall is on, box sites (e.g. php.kala) are inaccessible. Unchecking "Block all incoming connections" doesn't fix it. They don't work until you turn the firewall off completely.

We should figure out what settings are needed for the firewall to allow access to the box, then provide instructions for users that need them.

**Comment by whastings** [comment]
This article might help with opening up a path to NFS through the firewall:

http://www.williamrobertson.net/documents/nfs-mac-linux-setup.html

**Comment by pirog** [comment]
good to know. definitely annoying behavior.

**Comment by whastings** [comment]
Here's an issue on the Vagrant queue where some people posted solutions that worked for them:

https://github.com/mitchellh/vagrant/issues/1093

The answer from dkubb looks like it might be a good try.

**Comment by pirog** [comment]
I added a trello card for adding the firewall issue to our help docs .. however it also looks like https://github.com/mitchellh/vagrant/issues/1093#issuecomment-17209368 might address #6 ?

**Comment by pirog** [comment]
@reynoldsalec... can we close this out?

**Comment by pirog** [comment]
if people are still having this issue please consult
https://kalamuna.atlassian.net/wiki/display/kalabox/Troubleshooting+Kalabox+Problems
