### ISSUE TITLE
Download and Use Ubuntu 32-bit on 32-bit Machines

### ISSUE THREAD

**Issue by whastings** [kalamuna/kalastack#47]
@pirog Now that "vagrant up" handles downloading the .box file and adding it to Vagrant, could we add some logic that will cause it to use a 32-bit version of the .box file if the host machine is 32-bit? For now, I noted in the README's Quickstart section that Kalastack uses a 64-bit VM.

**Comment by pirog** [comment]
yes... i know this was in the backlog for awhile but might have been lost during recent cleanup. think this is a great idea.

**Comment by whastings** [comment]
I created a little wiki page for manually using the 32-bit Ubuntu image and linked to it from the requirements section of the README. We can remove these after this issue is resolved.

**Comment by pirog** [comment]
this should be in the next release.
