### ISSUE TITLE
Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find node 'kala.e823cb0a-daff-459a-a2fd-37d61808551b.f04083c46d392c7c7276a3570a96d095.box'; cannot compile

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastack#5]
``` bash
$ vagrant up kalabox --provision-with=shell,puppet_server
```

output:

``` bash
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

FACTER_vagrant='1' FACTER_kalauser='vagrant' FACTER_kalahost='192.168.42.1' puppet agent --verbose --debug --test --server kalabox.kalamuna.com --detailed-exitcodes || [ $? -eq 2 ]
```

**Comment by pirog** [comment]
why do you think this has to do with facter?

**Comment by pirog** [comment]
because the actual issue is: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find node 'kala.e823cb0a-daff-459a-a2fd-37d61808551b.f04083c46d392c7c7276a3570a96d095.box'; cannot compile

renaming issue.

**Comment by pirog** [comment]
i would try this whole thing from scratch and report back

**Comment by chriz001** [comment]
same problem here, my first sign of a problem is this

stdin: is not a tty
...
dpkg-preconfigure: unable to re-open stdin: No such file or directory
...
followed by the same error.

**Comment by andrewmallis** [comment]
we're having a bit of an issue between the box communication and the puppet server. You can try to build the box (temporarily) using the method described [in the wiki](https://github.com/kalamuna/kalastack/wiki/How-to-Participate) with the local puppet definitions. Or, hang tight till we solve this issue!

```
$ vagrant up kalabox --provision-with=shell,puppet
```

n.b. the stdin warning is unrelated to the build process

**Comment by chriz001** [comment]
Kalabox 2 Hello.

That Worked! 
Will give it another go when the communication issues are solved. Thanks!

**Comment by pirog** [comment]
Hoping to have this resolved in the next couple of days.

**Comment by thamas** [comment]
Same issue here. Local puppet definitions does not work too.

Lots of errors, the last lines:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chmod +x /tmp/vagrant-shell && /tmp/vagrant-shell
```

**Comment by pirog** [comment]
have pushed up some new code and tagged an alpha2 release that after basic testing appears to resolve this issue. would be great to get some feedback from you guys to see if this is the case!

**Comment by thamas** [comment]
Git pull than `vagrant up kalabox --provision-with=shell,puppet_server` run flawlessly. I see start.kala page in the browser on host machine. That is the result of my short, quick test. Cool! :)
