### ISSUE TITLE
Installation instructions inconsistent with Vagrantfile config

### ISSUE THREAD

**Issue by dwoods** [kalamuna/kalastack#56]
Following the directions in the README will result in a non-functional install.  The README uses ~/kalastack, but the NFS shared folder config in the Vagrantfile points to ~/kalabox.

**Comment by pirog** [comment]
This shouldn't make a different. You can actually put the kalastack code wherever you want, ~/kalastack, /Something/Something/Something/Darkside, ~/Documents/MyStack. 

I'm actually running mine from ~/.kalabox/kalastack. 
That said the shared folders are indeed mounted at ~/kalabox but this shouldn't make a difference. 

If you could tell me the ID of your stack by running
cat ~/kalastack/.kalabox/uuid 
i can see if there are any errors coming in for that install. 

Alternatively you can try again but i would make sure you first vagrant destroy the failed build, delete your kalastack directory completely and then redownload and re build.

**Comment by dwoods** [comment]
Ah, okay.  Must have just been a coincidence then - me reinstalling into ~/kalabox and then it working the second time.   

uuid file contains kala.3a81d314d2de51887985e7c563c1eec8.box

My versions:
- Vagrant is 1.2.2
- Virtualbox 4.2.16.

**Comment by pirog** [comment]
@dwoods thanks a bunch for trying again. i see a successful build report for 3a81d314d2de51887985e7c563c1eec8 so thats good!

we only "officially" support VB 4.2.8 but im glad to know it seems to be working on 4.2.16 !!!
