### ISSUE TITLE
NFS issues on OS X

### ISSUE THREAD

**Issue by kellybell** [kalamuna/kalastack#6]
Hi!
I received this error at the end of the README (https://github.com/kalamuna/kalastack/blob/2.x/README.md). 
(Running Mountain Lion.)
Thoughts?

```
    Mounting NFS shared folders failed. This is most often caused by the NFS
client software not being installed on the guest machine. Please verify
that the NFS client software is properly installed, and consult any resources
specific to the linux distro you're using for more information on how to
do this."
```

Thanks,
KBELL

**Comment by pirog** [comment]
Also had this issue early on when doing the port to vagrant but has since vanished. Also using OSX ML... have you tried this again?

**Comment by pirog** [comment]
@kellybell have you tried this again recently?

**Comment by pirog** [comment]
@kellybell checking in on this again. 

we seem to get this issue intermittently albeit infrequently but cant seem to isolate the source.

**Comment by andrewmallis** [comment]
Updated issue to more generically refer to OS X, since the issue was observed on 10.6.8 yesterday as well.

**Comment by pirog** [comment]
just got this error testing on 10.7.5... but just halted the box, ran the command again and it worked fine... maybe this is just ghosts in the machine.

**Comment by pirog** [comment]
https://github.com/mitchellh/vagrant/issues/1093#issuecomment-17209368

**Comment by pirog** [comment]
I _think_ this should be resolved in rc3

**Comment by pirog** [comment]
This worked but introduced other errors, reopening and likely reverting.

**Comment by pirog** [comment]
So the actual issue here seems to be one of two things. 
1. You don't have at least NFS version 3 which seems unlikely
2. You have enabled the "Block all incoming connections" option in MacOSX's Firewall
