### ISSUE TITLE
Install directions differences between wiki and front page

### ISSUE THREAD

**Issue by CalebGilbert** [kalamuna/kalastack#62]
After a bit of tinkering around I got everything working well. A few things:
1. The instructions of the front page/readme are different than the instructions in the wiki. The wiki includes this command:

<code>vagrant plugin install vagrant-vbguest</code>

...which the front page/readme does not. It appears that the front page/read me is the correct one (e.g., the command listed on the wiki is not needed).
1. Trying to install from the master branch didn't work for me, but downloading the rc3  did.
2. For what is worth, Kalabox seems to work fine of OSX 10.6.x

Thanks!

BTW - what is the status of this project in regard to proviso? I see proviso mentioned in the wiki, so that means that development efforts will be stopping here and focus will be put there?

**Comment by pirog** [comment]
@CalebGilbert, thanks for pointing this out! I've corrected the documents.

Weird that the master branch did not work... at the time of your post MASTER and RC3 were the same i think. 

So Kalamuna was one of the orgs present during the conversation that ultimately led to provisos birth. We have put some effort into the project but not as much as we would like to. Kalastack currently powers our "soon to be released" GUI dev environment tool Kalabox. 

We will be working on Kalastack until we get a stable version of kalabox out and then we are hoping to throw in completely with proviso with the hope it will eventually be the backend to kalabox, not kalastack. 

If you are interested in trying out the alpha version GUI tool of kalastack send me a message and i'll hook you up with a download link.

![screen shot 2013-10-01 at 5 15 08 pm](https://f.cloud.github.com/assets/713424/1250408/1baab87e-2af8-11e3-9771-fa6af1d4cfa4.png)
