### ISSUE TITLE
Success in Klingon is wrong

### ISSUE THREAD

**Issue by labboy0276** [kalamuna/kalastack#68]
you have it as Q'Plah, it should be Qapla'

**Comment by pirog** [comment]
@labboy0276 this is a critical hotfix which deserves immediate attention. thanks for your diligence here.

**Comment by labboy0276** [comment]
luckily I read the The Star Trek Encyclopedia 20+ years ago, this could of brought us down

**Comment by pirog** [comment]
I'm just really glad we cleaned this disgrace up before the public release. 

I take full responsibility.
