### ISSUE TITLE
Possibility of Integration with Aegir?

### ISSUE THREAD

**Issue by chriz001** [kalamuna/kalastack#8]
Are there any plans, or possibility of integrating kalastack with aegir? http://www.aegirproject.org/ 

I know it has been built to work with pantheon, but it would also be useful to work with aegir based sites aswell. 

If thats not a possibility, will there be plans to be able to import a site manually?

cheers.

**Comment by pirog** [comment]
Long term goal is for users to be able to spin up new sites using their favorite distros and to be able to import preexisting sites manually. 

Would love to add more integration points such as with Aegir or Acquia as well and for users to be able to rebuild their box using different chef/puppet recipes.

**Comment by chriz001** [comment]
Sounds good. Guess i will keep my eye on this one. 

Thanks.

**Comment by pirog** [comment]
Give us a look-see around DrupalCon Portland :)

**Comment by chriz001** [comment]
Will do :)

**Comment by pirog** [comment]
there is an open source initiative that is happening that we are involved in and that might be a better sounding board for this issue. 
https://github.com/proviso/proviso

**Comment by andrewmallis** [comment]
@chriz001 you might want to check out https://drupal.org/project/valkyrie and https://drupal.org/project/devshop two fledgeling Aegir-based projects.
