### ISSUE TITLE
Feature request: Allow pasting into Pantheon password field

### ISSUE THREAD

**Issue by agold2** [kalamuna/kalastack#81]
I use a password manager (KeePassX) to generate strong passwords I don't need to know or ever type. I tried to paste my Pantheon password with no luck.

**Comment by pirog** [comment]
Is this request for Kalastack or for Kalabox?

**Comment by agold2** [comment]
Kalabox. sorry...is there an issue queue for Kalabox?

**Comment by pirog** [comment]
http://www.kalamuna.com/products/kalabox/
support tab on the right!

That said. We do have this issue in our tracker and it is slated to be
addressed in the next release!

On Tue, Feb 11, 2014 at 7:44 PM, agold2 notifications@github.com wrote:

> Kalabox. sorry...is there an issue queue for Kalabox?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/kalamuna/kalastack/issues/81#issuecomment-34826747
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by agold2** [comment]
Excellent. Thanks, Mike!

**Comment by pirog** [comment]
This should be GTG in latest Beta5 and upcomgin beta6!
