### ISSUE TITLE
Performance - an open question

### ISSUE THREAD

**Issue by bassettsj** [kalamuna/kalastack#82]
I totally understand that vagrant is always going to be slower by nature, but I am wondering if there might be an optional puppet module to help set up redis for some caching on the environment to help make the drupal sites more performant and make the environment a little more similar to  Pantheon's.  I could be totally off, but I think this could be a nice addition to the puppet provisioning process. What are your thoughts?

**Comment by pirog** [comment]
One of the priorities with kalastack was keeping it as lean as possible, which is why it doesn't ship with solr by default. We needed spin up times for kalabox to be as small as possible since it takes a bit to set up a whole webserver. 

That said it's pretty straightforward to install redis on Ubuntu 12.04 and we could offer it as a one click post-install add on like SOLR. 

Are you experiencing slowness on all your sites or just a few? Generally, unless you are dealing with a site that is super fucked up or just using a really old machine which desires more RAM sites should be loading very quickly... especially after APC and other tools start kicking in.

**Comment by bassettsj** [comment]
Well this site is probably not tuned the best it can be, so I am not shocked that the performance isn't decent. The site itself is also huge, with around 50,000 nodes.

I also think my development workflow is a little more demanding in terms of needing a lot of page refreshes to see the changes in CSS styles or templates rendering.

I agree that keeping the base stack as light as possible is important, so I think this should definitely be similar to setting up solr. I played around with adding redis to that slow site and saw some much better performance. Creating a simple optional manifest that could help streamline that for users who want it

**Comment by pirog** [comment]
Awesome!

Let's work on implementing this when we are both around!

On Mon, Feb 17, 2014 at 4:18 PM, Steven Bassett notifications@github.comwrote:

> Well this site is probably not tuned the best it can be, so I am not
> shocked that the performance isn't decent. The site itself is also huge,
> with around 50,000 nodes.
> 
> I also think my development workflow is a little more demanding in terms
> of needing a lot of page refreshes to see the changes in CSS styles or
> templates rendering.
> 
> I agree that keeping the base stack as light as possible is important, so
> I think this should definitely be similar to setting up solr. I played
> around with adding redis to that slow site and saw some much better
> performance. Creating a simple optional manifest that could help streamline
> that for users who want it
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/kalamuna/kalastack/issues/82#issuecomment-35323779
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by bassettsj** [comment]
Cool, I might fork it and learn a bit about Puppet and we can go from
there, maybe get a pull-request to work from.

**Comment by pirog** [comment]
I like pull requests :)

Puppet is a declarative language so its a little different from php in that
way. there are some good open source redis modules out there and moving to
underlying open source mods is something we want to do with a lot of things
in kalastack.

in the meantime... the way solr is set up as an additional manifest is
probably the way we want to go for now.

On Mon, Feb 17, 2014 at 4:31 PM, Steven Bassett notifications@github.comwrote:

> Cool, I might fork it and learn a bit about Puppet and we can go from
> there, maybe get a pull-request to work from.
> 
> On Mon, Feb 17, 2014 at 4:20 PM, Michael Pirog notifications@github.comwrote:
> 
> > Awesome!
> > 
> > Let's work on implementing this when we are both around!
> > 
> > On Mon, Feb 17, 2014 at 4:18 PM, Steven Bassett <
> > notifications@github.com
> > 
> > > wrote:
> > > 
> > > Well this site is probably not tuned the best it can be, so I am not
> > > shocked that the performance isn't decent. The site itself is also
> > > huge,
> > > with around 50,000 nodes.
> > > 
> > > I also think my development workflow is a little more demanding in
> > > terms
> > > of needing a lot of page refreshes to see the changes in CSS styles or
> > > templates rendering.
> > > 
> > > I agree that keeping the base stack as light as possible is important,
> > > so
> > > I think this should definitely be similar to setting up solr. I played
> > > around with adding redis to that slow site and saw some much better
> > > performance. Creating a simple optional manifest that could help
> > > streamline
> > > that for users who want it
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/kalamuna/kalastack/issues/82#issuecomment-35323779>
> > > .
> > 
> > ## 
> > 
> > Cheers,
> > 
> > Mike Pirog
> > Kalamuna
> > www.kalamuna.com
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/kalamuna/kalastack/issues/82#issuecomment-35323882>
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/kalamuna/kalastack/issues/82#issuecomment-35324680
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com
