### ISSUE TITLE
start.kala fails after install

### ISSUE THREAD

**Issue by HenrikBechmann** [kalamuna/kalastack#85]
Hi there,

I've just installed kalastack onto my new macbook pro (Mavericks; Vagrant 1.6.3; Virtualbox 4.3.12)

... but when I try start.kala in a browser, I get "502 Bad Gateway (nginx/1.1.19)"

Also ~/kalabox/www is empty.

I've been using Kalastack 2 (I presume 2 - I've been using it for a while) on my work desktop.

Is this a known issue on Mavericks?

Any ideas?

Thanks

**Comment by reynoldsalec** [comment]
Did you try installing the 3.x branch from Github? That's the latest stuff, it's what we use on Kalabox.

I believe /kalabox/www should be empty when you first install the stack; the start.kala content isn't stored there.

I would check and make sure the virtual hosts were setup correctly on your virtual machine; check /etc/nginx/sites-avialable to see if the "start" vhost exists and check /etc/hosts on the virtual machine to make sure that start.kala has an entry.

Did you install with Kalabox, or just independently install kalastack?

**Comment by HenrikBechmann** [comment]
yes 3.x from github.

I'll check virtual hosts, thanks

I just installed kalastack

**Comment by reynoldsalec** [comment]
Cool, guessing you've tried restarting the virtual machine as well?

If you continue having problems you'll probably want to check the nginx error log (/var/log/nginx/error.log) and paste that here.

**Comment by HenrikBechmann** [comment]
yeah, restarted

etc/hosts on the vm:

```
1.3.3.1 host.kala
127.0.0.1       localhost
127.0.1.1 kala.0ef9b78059fb641b302eda21a4389155.box kala
```

I added

```
1.3.3.1 start.kala
```

but it didn't help

checking nginx sitesavailable next

**Comment by pirog** [comment]
i am pretty sure 1.3.3.7 should be the IP address? Did that change somehow?

On Tue, Jun 24, 2014 at 5:57 PM, Henrik Bechmann notifications@github.com
wrote:

> yeah, restarted
> 
> etc/hosts on the vm:
> 
> 1.3.3.1 host.kala
> 127.0.0.1       localhost
> 127.0.1.1 kala.0ef9b78059fb641b302eda21a4389155.box kala
> 
> I added
> 
> 1.3.3.1 start.kala
> 
> but it didn't help
> 
> checking nginx sitesavailable next
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalastack/issues/85#issuecomment-47049274.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
Also, https://github.com/kalamuna/kalabox/issues/23 may be worth coordinating with.

**Comment by HenrikBechmann** [comment]
sites-enabled/start looks ok

/usr/share/kalabox/index.php looks ok

error.log is filled with these:

```
2014/06/25 00:55:08 [crit] 886#0: *1 connect() to unix:/tmp/php-fpm.sock failed (13: Permission
denied) while connecting to upstream, client: 1.3.3.1, server: start.kala, request: "GET / HTTP/1.1",
upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "start.kala"
```

**Comment by pirog** [comment]
try changing the IPs to 1.3.3.7 in /etc/hosts on mac and see what happens.

On Tue, Jun 24, 2014 at 6:03 PM, Henrik Bechmann notifications@github.com
wrote:

> sites-enabled/start looks ok
> 
> /usr/share/kalabox/index.php looks ok
> 
> error.log is filled with these:
> 
> 2014/06/25 00:55:08 [crit] 886#0: *1 connect() to unix:/tmp/php-fpm.sock failed (13: Permission
> denied) while connecting to upstream, client: 1.3.3.1, server: start.kala, request: "GET / HTTP/1.1",
> upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "start.kala"
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalastack/issues/85#issuecomment-47049615.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by HenrikBechmann** [comment]
already is:

```
 1.3.3.7  start.kala  # VAGRANT: e93914....
```

What about instructions here: http://www.nginxtips.com/php5-fpm-sock-failed-13-permission-denied-error/

?

**Comment by pirog** [comment]
whoops! my bad... thought you were reporting etc/hosts on mac not on VM.
those are correct then.

the article you posted looks very relevant. can you try that out and let it
know if it resolves your issue? the socket should be in /tmp as well for
kalastack. please report whether it has the wrong owner!

On Tue, Jun 24, 2014 at 6:09 PM, Henrik Bechmann notifications@github.com
wrote:

> already is:
> 
>  1.3.3.7  start.kala  # VAGRANT: e93914....
> 
> What about instructions here:
> http://www.nginxtips.com/php5-fpm-sock-failed-13-permission-denied-error/
> 
> ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalastack/issues/85#issuecomment-47049938.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by HenrikBechmann** [comment]
mañana :-P but I'll definitely get back to you. Thanks!

**Comment by pirog** [comment]
can't argue with manana :)
thanks for your help with this!

On Tue, Jun 24, 2014 at 6:17 PM, Henrik Bechmann notifications@github.com
wrote:

> mañana :-P but I'll definitely get back to you. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalastack/issues/85#issuecomment-47050399.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by HenrikBechmann** [comment]
I just tried user nginx - failed on restart, probably 'cause there's only one user: vagrant. ;-)

```
root@kala:/home/vagrant# users
vagrant
```

I'll try the rest tomorrow.

**Comment by Nitty-Gritty** [comment]
I'm having the same "502 Bad Gateway nginx/1.1.19" error. 

I've installed kalastack with Vagrant 1.3.5 and VirtualBox 2.4.18 (virtualbox-4.2_4.2.18-88780~Ubuntu~raring_i386.deb) on Mint 17. 

Cloning kalastack through git appeared to work but I had NFS errors. Installing "nfs-common" solved that. Trying http://start.kala gave "server not found". nginx wasn't initially installed so I did that manually. Now I have the nginx folder with a sites-available folder as reynoldsalec describes, but the only file in there is "default" and it does not contain "start". etc/hosts doesn't exist in Mint but I'm not sure how to check if it exists on the virtual machine.

Does this Bad Gateway issue sound like it has the same cause as HenrikBechmann? Or should I start another issue?

**Comment by reynoldsalec** [comment]
@Nitty-Gritty that sounds different, seems like the virtual environment wasn't provisioned correctly if nginx wasn't installed. You might try re-building Kalastack now that you have nfs-common installed on your host machine.

I know that some Ubuntu users have needed to change the nfs_version to 4 in the default.config.json file: https://github.com/kalamuna/kalastack/wiki/Tips-for-Installing-on-Ubuntu-Linux

If you have any further issues, open up a new issue and we'll see what we can do!

**Comment by pirog** [comment]
I would try out the resolution proposed here https://github.com/kalamuna/kalabox/issues/23

**Comment by pirog** [comment]
Can confirm that https://github.com/kalamuna/kalabox/issues/23 is actually this underlying Kalastack issue

**Comment by pirog** [comment]
The easiest fix for this as of right now is to SSH into the box or stack and run 

```
$ sudo chown vagrant:vagrant /tmp/php-fpm.sock
```

**Comment by pirog** [comment]
commit below should resolve the issue if people want to apply manually for now

**Comment by pirog** [comment]
Rebuilt from HEAD and it seems to resolve. Would be great for others to test. Destroy your vagrant env, pull latest code, build locally as per https://github.com/kalamuna/kalastack/wiki/How-to-Participate and it should be g2g.

**Comment by HenrikBechmann** [comment]
@pirog 

```
sudo chown vagrant:vagrant /tmp/php-fpm.sock
```

fixed the problem

Thanks!!! You're the best

**Comment by pirog** [comment]
Ha! NO YOURE THE BEST!

**Comment by Nitty-Gritty** [comment]
You're ALL the best!!! The speed that this fix was developed at meant I was able to meet this scholarship trust founder today and not look as dumb as picking a previously untested distro 2 days prior to the meeting suggests I am :D

btw, I hope Pantheon realise what a huge draw card the Kalabox kickstarter would be to them and at least complete the goal. Even now Kalamuna is funnelling designers like me right to them!

**Comment by pirog** [comment]
THANKS SO MUCH!

We hope they do too... and we hope other platform providers see the
potential. We certainly think there is a lot.

On Thu, Jun 26, 2014 at 1:29 AM, Nitty-Gritty notifications@github.com
wrote:

> You're ALL the best!!! The speed that this fix was developed at meant I
> was able to meet this scholarship trust founder today and not look as dumb
> as picking a previously untested distro 2 days prior to the meeting
> suggests I am :D
> 
> btw, I hope Pantheon realise what a huge draw card the Kalabox kickstarter
> would be to them and at least complete the goal. Even now Kalamuna is
> funnelling designers like me right to them!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalastack/issues/85#issuecomment-47200180.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by HenrikBechmann** [comment]
Mike, just to confirm that I destroyed and rebuilt kalastack per your instructions above and all is good.

Thanks again.
- Henrik

**Comment by pirog** [comment]
awesome! glad to hear it.
