### ISSUE TITLE
Example of use

### ISSUE THREAD

**Issue by thamas** [kalamuna/kalastack#9]
I know you held more demonstrations about kalastack. Did someone recorded them? It wouold be good to see an example from live practice how to use kalastack. For example a basic question: is kalastack designed to use as a permanent local dev server for multiple project or shpuld we build a new machine for every project (vagrant default style)?

**Comment by pirog** [comment]
i suppose you could do either. right now we are using it for multiple projects which has some resource pool issues right now that we are working on fixing. the multiple machine paradigm might be difficult given the finite resources of the computer you are using.

**Comment by pirog** [comment]
@andrewmallis has also provided some updated info in the readme and added some docs to the wiki that might be helpful!

**Comment by thamas** [comment]
I'll check them. Thanks!
