### ISSUE TITLE
Mounting NFS shared folders fails / gets stuck

### ISSUE THREAD

**Issue by labboy0276** [kalamuna/kalastack#92]
OK

So i have spent all day trying to rebuild my stack.  I am constantly getting stuck at Mounting NFS shared folders.  In logging mode I get this:

INFO ssh: Setting SSH_AUTH_SOCK remotely: /tmp/ssh-rdpYNa1012/agent.1012
INFO retryable: Retryable exception raised: #<Vagrant::Errors::LinuxNFSMountFailed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 1.3.3.1:'/home/john/kalabox/www' /var/www

Stdout from the command:

Stderr from the command:

stdin: is not a tty
mount.nfs: mount to NFS server '1.3.3.1:/home/john/kalabox/www' failed: timed out, giving up

**Comment by labboy0276** [comment]
I ended up winning this after all, what I did was:

change my nfs to version 4 in the default.config
i cleared out (not delete) the contents of /etc/exports in my OS and in my box (vagrant ssh still worked even tho it was fubared)
vagrant destroy
restarted
vagrant up

**Comment by pirog** [comment]
@reynoldsalec i think there are some other tickets relating to timeout maybe we can point those users here to try this out and confirm?

**Comment by reynoldsalec** [comment]
To anyone using these instructions, be clear that you will want to backup the database of any sites you have on the Kalabox before running, since running "vagrant destroy" will wipe the virtualmachine.

**Comment by therobyouknow** [comment]
@labboy0276 "change my nfs to version 4 in the default.config" - can you provide more detail about changing to version 4. I've search on google quite extensively and there doesn't seem to be a definitive answer to 1) know what version I have 2) then upgrade to v4 (if using v3).

My system: Ubuntu 14.04 LTS 64bit on 8Gb i7 2.0Ghz ThinkPad X201S (host machine)

Wanting to run Ubuntu 12.04 LTS 64 bit as guest VM

**Comment by labboy0276** [comment]
@therobyouknow In your kalastack folder there is a file called default.config.json

Find this  "nfs_version": "3", 
change to  "nfs_version": "4",

**Comment by saurabhguptaDoingCS** [comment]
@labboy0276  I am using latest vagrant(1.8.6) on OSX 10.11.6 (El Capitan) and trying running ubuntu16.04.1 LTS on docker and getting this same error.

Can you please tell me "how to change the nfs_version on mac?"

**Comment by labboy0276** [comment]
@saurabhguptaDoingCS this repo has been depreciated for many years now.  I would switch to kalabox 2.
