### ISSUE TITLE
We should install vim by default

### ISSUE THREAD

**Issue by pandaPowder** [kalamuna/kalastack#94]
I created a pull request to install vim. I hope I did it right :)
https://github.com/kalamuna/kalastack/pull/93

**Comment by pirog** [comment]
I _think_ that you can use "vi" in kalastack by default which is normally what i do. Also think "nano" is available. Are either of those not sufficient for your needs?

That said... yes you did it right and i really dig the name of the issue/PR. We def want to maximize our days with sunshine for sure :)

**Comment by pandaPowder** [comment]
I just verified that vi is there and based on the splash screen it is really vim. I rescind my pull request in that case. However, would it be worth an alias or something so that people don't get confused like I did? Or maybe more people try vi first. I don't know. Thanks!

**Comment by pirog** [comment]
i've always just used "vi" but an alias might be fine as well if you want to PR that instead!

**Comment by pandaPowder** [comment]
if I can figure out how to do that I will shoot one over. Thanks!

**Comment by reynoldsalec** [comment]
FYI, I think technically this is vi; if you run "sudo apt-get install vim"
it'll install the actual vim package. So having any alias might be more
confusing than not...

On Thu, Jul 17, 2014 at 3:44 PM, pandaPowder notifications@github.com
wrote:

> if I can figure out how to do that I will shoot one over. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalastack/issues/94#issuecomment-49376334.

## 

Co-founder Kalamuna, LLC http://www.kalamuna.com
510.666.5489
Skype: alec.kalamuna

**Comment by pirog** [comment]
Yeah that might be weird and confusing. I'm going to close the issue on those grounds but @pandaPowder feel free to reopen if you think we should try to do something else here.
