### ISSUE TITLE
Add Front-End Development Tools

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastack#96]
Add a number of front-end ops tools. There's a list here of things that I've been using for front-end ops stuff:
https://github.com/RobLoach/forge/tree/master/forge#features

**Comment by pirog** [comment]
For the purposes of this issue we probably really only need to add in the node/ruby requirements into the stack. 

@gremy is this something you can help with? if so please ping me so i can show you the kalastack stuff real quickly before you begin.

**Comment by gremy** [comment]
@pirog I sure can. How about I add the front-end stuff in the puppet script.

**Comment by pirog** [comment]
yeah thats good, lets just talk for about 10 minutes before you go for it!
and open a branch up for it.

On Thu, Sep 25, 2014 at 4:13 PM, Emanuel Greucean notifications@github.com
wrote:

> @pirog https://github.com/pirog I sure can. How about I add the
> front-end stuff in the puppet script.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalamuna/kalastack/issues/96#issuecomment-56898283.

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
@gremy here is a cheap and dirty way to get the latest stable node installed
https://github.com/pirog/kalastack/commit/057165acb9ebea11075c132f2530d06188a8dcb5

After `vagrant up` you should get something like this
![screen shot 2014-09-27 at 3 36 31 pm](https://cloud.githubusercontent.com/assets/713424/4432494/f800e950-4696-11e4-865c-9217acf625dc.png)

**Comment by RobLoach** [comment]
Less than an hour?

**Comment by pirog** [comment]
![screen shot 2014-09-27 at 3 40 24 pm](https://cloud.githubusercontent.com/assets/713424/4432497/4f0efd22-4697-11e4-8269-93155327fceb.png)

**Comment by pirog** [comment]
I haven't installed the rest of the tooling stuff though which i _did_ say i would do in less than an hour... but i've still got time :)

that said @gremy, i think this was the only blocker for you so if you want to merge it in and take it rest of the way feel free :)

**Comment by pirog** [comment]
![image](https://cloud.githubusercontent.com/assets/713424/4432514/6a6e9838-4698-11e4-8843-f284c6c2339d.png)

**Comment by RobLoach** [comment]
https://github.com/pirog/kalastack/pull/1

Need a new machine to do any kind of virtualization. This is just way too slow to test.
